VS/Infestation/Infestation/Models/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Infestation.Models
{
    public class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Population { get; set; }
        public int SickCount { get; set; }
        public int DeadCount { get; set; }
        public int RecoveredCount { get; set; }
        public bool Vaccine { get; set; }

        public int WorldPartId { get; set; }
        public virtual WorldPart WorldPart { get; set; }

        public virtual List<Human> Humans { get; set; }
    }
}

VS/Infestation/Infestation/Models/Human.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Infestation.Models
{
    public class Human
    {
        public int Id { get; set; }

        [Required]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Name must only countain")]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Range(1,150,ErrorMessage ="Age is out available")]
        public int Age { get; set; }

        [Required]
        public bool IsSick { get; set; }

        [Required]
        public string Gender { get; set; }


        [Range(1, 7, ErrorMessage = "CountryId is out available")]
        public int CountryId { get; set; }     
        public virtual Country Country { get; set; }
    }
}

VS/Infestation/Infestation/Controllers/HumanController.cs
using Infestation.Infrastucture.Configuration;
using Infestation.Models;
using Infestation.Models.Repositories;
using Infestation.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Infestation.Controllers
{
    public class HumanController : Controller
    {

        //private InfestationContext _context { get; set; }
        //public HumanController(InfestationContext context)
        //{
        //    _context = context;
        //}

        //public IActionResult Index(int humanId)
        //{
        //    List<Human> humen = null;

        //    if (humanId == 0)
        //    {
        //        humen = _context.Humans.ToList();

        //    }
        //    else
        //    {
        //        humen = new List<Human>(1);
        //        humen.Add(_context.Humans.SingleOrDefault(human => human.Id == humanId));
        //    }

        //    ViewData["human"] = humen;
        //    return View();
        //}
        //public IActionResult Country(string countryName)
        //{
        //    ViewData["country"] = _context.Countries.SingleOrDefault(country => country.Name == countryName).Humans;
        //    return View();
        //}


        private IHumanRepository _iHumanRepository { get; set; }
        public HumanController(IHumanRepository iHumanRepository)
        {
            _iHumanRepository = iHumanRepository;

        }

        
        [AllowAnonymous]
        public IActionResult Index(int humanId, string? countryName)
        {
                List<Human> humen = null;

            if (humanId == 0)
            {
                humen = _iHumanRepository.GetAllHumans();

            }
            else if (countryName != null)
            {
                humen = _iHumanRepository.GetAllHumansInCountry(countryName);
            }
            else
            {
                humen = new List<Human>(1);
                humen.Add(_iHumanRepository.GetHuman(humanId));
            }
                
            return View(humen);
        }

        [AllowAnonymous]
        public IActionResult Country(string _countryName)
        {
            //ViewData["humen"] = _iHumanRepository.GetAllHumansInCountry(countryName);
            return RedirectToAction("Index", "Human",new { humanId = 2, countryName= _countryName });
            //return View(_iHumanRepository.GetAllHumansInCountry(countryName));
        }

        [AllowAnonymous]
        public IActionResult Authors([FromServices] INewsRepository newsRepository, int AuthorsId=0) 
        {
            var humans = _iHumanRepository.GetAllHumans().ToList();
            var news = newsRepository.GetAllNews().ToList();
            var viewModels = new List<HumanAuthorsViewModel>();

            if (AuthorsId != 0)
            {
                var human = humans.FirstOrDefault(_human => _human.Id == AuthorsId);
                var viewModel = new HumanAuthorsViewModel();
                viewModel.AuthorId = human.Id;
                viewModel.FirstName = human.FirstName;
                viewModel.LastName = human.LastName;

                viewModel.NewsCount = news.Count(news => news.AuthorId == human.Id);

                viewModels.Add(viewModel);


                return View(viewModels);
            }

            foreach (var human in humans)
            {
                var viewModel = new HumanAuthorsViewModel();
                viewModel.AuthorId = human.Id;
                viewModel.FirstName = human.FirstName;
                viewModel.LastName = human.LastName;

                viewModel.NewsCount = news.Count(news=>news.AuthorId==human.Id);

                viewModels.Add(viewModel);
            }
            
            return View(viewModels);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Human human)
        {
            if(ModelState.IsValid)
                _iHumanRepository.CreateHuman(human);

            return View();
        }

        //Id=2&FirstName=Nikola&LastName=Gogol&type=47&IsSick=on&Gender=Male&CountryId=5
    }
}

VS/Infestation/Infestation/Controllers/NewsController.cs
using Infestation.Models;
using Infestation.Models.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Infestation.Controllers
{
      
    public class NewsController : Controller
    {
        private INewsRepository _repository { get; set; }

        public NewsController(INewsRepository repository)
        {
            _repository = repository;
        }

        
        public IActionResult Index(int id=-1)
        {

            List<News> news = null;

            if (id == -1)
            {
                news = _repository.GetAllNews().ToList();

            }
            else
            {
                news = new List<News>
                {
                    _repository.GetNews(id)
                };
            }

            return View(news);

        }

        public IActionResult Author (int authorsId)
        {
            List<News> aNews=_repository.GetAllAuthorsNews(authorsId);
            

            return View(aNews);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(News news)
        {
            if(ModelState.IsValid)
                _repository.CreateNews(news);

            return View();
        }
    }
}

VS/Infestation/Infestation/Views/Human/Authors.cshtml
@model List<HumanAuthorsViewModel>


    <table class="table">
        <tr>
            <th>AuthorId</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>NewsCount</th>
        </tr>
        @foreach (var author in Model)
        {
            <tr>
                <td>@author.AuthorId</td>
                <td>@author.FirstName</td>
                <td>@author.LastName</td>
                <td><a asp-controller="News" asp-action="Author" asp-route-authorsId="@author.AuthorId">@author.NewsCount</a></td>
            </tr>
        }
    </table>

VS/Infestation/Infestation/Views/Human/Country.cshtml
@model List<Human>

@foreach (var human in Model)
{
    <table>
        <tr>
            <td>Name human =</td>
            <td>@human.FirstName </td>
        </tr>

        
    </table>
    <h1>------------------------------------------------------</h1>
    <p></p>

}

VS/Infestation/Infestation/Views/Human/Create.cshtml
@model Human

    <form asp-controller="Human" asp-action="Create" method="post">
        @*<div asp-validation-summary="All"></div>*@
        <label asp-for="FirstName" for="FirstName">FirstName</label><br>
        <input asp-for="FirstName" name="FirstName" type="text" /><br>
        <span class="text-danger" asp-validation-for="FirstName"></span><br>

        <label asp-for="LastName">LastName</label><br>
        <input asp-for="LastName" type="text" /><br>
        <span class="text-danger" asp-validation-for="LastName"></span><br>

        <label asp-for="Age">Age</label><br>
        <input asp-for="Age" type="number" /><br>
        <span class="text-danger" asp-validation-for="Age"></span><br>

        <label asp-for="IsSick">IsSick</label><br>
        <input asp-for="IsSick" type="checkbox" /><br>

        <label asp-for="Gender">Gender</label><br>
        <input asp-for="Gender" type="text" /><br>
        <span class="text-danger" asp-validation-for="Gender"></span><br>

        <label asp-for="CountryId">CountryId</label><br>
        <input asp-for="CountryId" type="number" /><br>
        <span class="text-danger" asp-validation-for="CountryId"></span><br>

        <button type="submit">Create human</button>

    </form>

VS/Infestation/Infestation/Views/Human/Index.cshtml
@model List<Human>


@if (Model != null)
{
    <table class="table">
        <tr>
            <th>Id</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Age</th>
            <th>IsSick</th>
            <th>Gender</th>
        </tr>
        @foreach (var human in Model)
        {
            <tr>
                <td>@human.Id</td>
                <td>@human.FirstName</td>
                <td>@human.LastName</td>
                <td>@human.Age</td>
                <td>@human.IsSick</td>
                <td>@human.Gender</td>
            </tr>
        }
    </table>
}